// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MovieCardController from "./movie_card_controller"
application.register("movie-card", MovieCardController)

import MovieCategoryController from "./movie_category_controller"
application.register("movie-category", MovieCategoryController)
